name: Authenticate & Run Commands on Google Cloud

on:
  push:
    branches:
      - main
    paths:
      - 'gcp/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: # Grant permissions to the workflow
      contents: read
      id-token: write


    steps:
        # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

        # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

        # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

        # Run an arbitrary gcloud command
      - name: List Google Cloud Projects
        run: |
          gcloud projects list
