# Deploy an image in ECR to Lambda

name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/aws_ghar.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
            aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.AWS_ECR_REGISTRY }}
# Invoke the lambda function called gha-runner
      - name: Invoke Lambda function
        run: |
            aws lambda invoke --function-name gha-runner --payload '{}' response.json