name: Hi Mascot

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - '.github/workflows/first.yml'

env: # env for all jobs
  mascot: Mona
  super_duper_var: totally_awesome

jobs:
  windows_job:
    runs-on: windows-latest
    steps:
      - run: echo 'Hi ${{ env.mascot }}'  # Hi Mona
      - run: echo 'Hi ${{ env.mascot }}'  # Hi Mona
      - run: echo 'Hi ${{ env.super_duper_var }}' 
        env: # env for this job
          mascot: Octocat
  linux_job:
    runs-on: ubuntu-latest
    env:
      mascot: Tux
    steps:
      - run: echo 'Hi ${{ env.mascot }}'  # Hi Tux

  self_hosted_job:
    runs-on: self-hosted
    steps:
      - run: echo 'Hi ${{ env.mascot }}'  # Hi Mona
# add a wait command for 30 seconds
      - run: wait 30
      - run: echo 'Hi Sam'
