name: GH Actions Runner with Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/gcp_runners.yml'
      - 'Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/gcp_runners.yml'
      - 'Dockerfile'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      id-token: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

        # Authenticate to Google Cloud
      - id: authenticate
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: Authenticate Docker with Google Artifact Registry
        run: |
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t actions-runner:latest --load .
          echo "Checking the Docker images"
          docker images

      - name: Tag Docker Image
        run: |
          docker tag actions-runner:latest ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID_VAL }}/my-repo/actions-runner:latest
          
      - name: Push Image to Google Artifact Registry
        run: |
          docker push ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID_VAL }}/my-repo/actions-runner:latest
