name: Build Dockerfile and Push to Google Cloud Artifact Registry

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/gcloud_auth.yml'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/gcloud_auth.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

        # Authenticate to Google Cloud
      - id: authenticate
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker gcr.io

      - name: Build Docker image
        run: docker build -t gcr.io/gh-actions-1506/my-self-hosted-runner:latest .

      - name: Push Docker image to Google Artifact Registry
        run: docker push gcr.io/gh-actions-1506/my-self-hosted-runner:latest