# Github actions workflow to build and push the docker image to azure container registry

name: Build Push GHAR Docker Image to ACR

on:
    push:
        branches:
        - main
        paths:
        - '.github/workflows/gharunner_docker_build_azure.yml'
        - 'Dockerfile'
    pull_request:
        branches:
        - main
        paths:
        - '.github/workflows/gharunner_docker_build_azure.yml'
        - 'Dockerfile'

jobs:
    docker-build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to Azure Container Registry
          uses: azure/docker-login@v1
          with:
            login-server: ${{ vars.ACR_REGISTRY }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}

        - name: Build Docker Image
          run: |
            docker buildx build --platform linux/amd64 -t gh-actions-runner:latest -f Dockerfile.ghrunner --load .
            echo "Checking the Docker images"
            docker images

        - name: Tag Docker Image
          run: |
            docker tag gh-actions-runner:latest ${{ vars.ACR_REGISTRY }}/my-repo/gh-actions-runner:latest

        - name: Push Image to Azure Container Registry
          run: |
            docker push ${{ vars.ACR_REGISTRY }}/my-repo/gh-actions-runner:latest