# Github actions workflow to build and push the docker image to aws elastic container registry

name: Build Push GHAR Docker Image to ECR

on:
    push:
        branches:
        - main
        paths:
        - '.github/workflows/gharunner_docker_build_aws.yml'
        - 'Dockerfile'
    pull_request:
        branches:
        - main
        paths:
        - '.github/workflows/gharunner_docker_build_aws.yml'
        - 'Dockerfile'

jobs:
    docker-build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to AWS Elastic Container Registry
          uses: aws-actions/amazon-ecr-login@v2
          with:
            region: ${{ vars.AWS_REGION }}
            access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        - name: Build Docker Image
          run: |
            docker buildx build --platform linux/amd64 -t gh-actions-runner:latest -f Dockerfile.ghrunner --load .
            echo "Checking the Docker images"
            docker images

        - name: Tag Docker Image
          run: |
            docker tag gh-actions-runner:latest ${{ vars.AWS_ECR_REGISTRY }}/gh-actions-runner:latest

        - name: Push Image to AWS Elastic Container Registry
          run: |
            docker push ${{ vars.AWS_ECR_REGISTRY }}/gh-actions-runner:latest