name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # This enables OIDC token generation
      contents: read   # To read the repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print OIDC Token Info
        run: |
          echo "Requesting OIDC Token"
          echo "Token URL: $ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "Token Request: $ACTIONS_ID_TOKEN_REQUEST_TOKEN"
          # Making a request to fetch the actual OIDC token
          curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq .
