name: Inspect OIDC Token Claims

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - '.github/workflows/oidc.yml'

jobs:
  inspect-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Allows OIDC token generation
      contents: read   # To access the repository contents

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get OIDC Token
      id: oidc-token
      run: |
        # Request the OIDC token
        OIDC_TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
        "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)

        echo "OIDC Token: $OIDC_TOKEN"

        # Function to handle URL-safe base64 and padding
        urlsafe_base64_decode() {
          local base64_input=$1
          # Replace URL-safe characters with standard base64 characters
          local base64_input_standard=$(echo "$base64_input" | sed 's/-/+/g; s/_/\//g')
          # Add padding if necessary
          local remainder=$((${#base64_input_standard} % 4))
          if [ "$remainder" -eq 2 ]; then
              base64_input_standard="${base64_input_standard}=="
          elif [ "$remainder" -eq 3 ]; then
              base64_input_standard="${base64_input_standard}="
          fi

          echo "$base64_input_standard" | base64 --decode 2>/dev/null
        }

    - name: Get OIDC Token and Decode Claims
      id: oidc-claims
      run: |
        # Request the OIDC token
        OIDC_TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
        "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)

        echo "::add-mask::$OIDC_TOKEN"

        payload=$(echo "$OIDC_TOKEN" | cut -d '.' -f2)

        # Ensure correct padding for base64 decoding
        padded_payload=$(echo "$payload" | sed -E 's/(-|_)+/+/g; s/_/\//g; s/.{4}$/&===/')

        # Attempt to decode the payload and handle errors
        decoded_payload=$(echo "$padded_payload" | base64 --decode 2>/dev/null || echo "Decode error")
        
        if [ "$decoded_payload" = "Decode error" ]; then
          echo "Failed to decode the OIDC token payload"
          exit 1
        else
          echo "Decoded OIDC Claims:"
          echo "$decoded_payload" | jq .
        fi

