name: Inspect OIDC Token Claims

on:
  workflow_dispatch:

jobs:
  inspect-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Allows OIDC token generation
      contents: read   # To access the repository contents

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get OIDC Token
      id: oidc-token
      run: |
        # Request the OIDC token
        OIDC_TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
        "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)

        echo "OIDC Token: $OIDC_TOKEN"

        # Function to handle URL-safe base64 and padding
        urlsafe_base64_decode() {
          local base64_input=$1
          # Replace URL-safe characters with standard base64 characters
          local base64_input_standard=$(echo "$base64_input" | sed 's/-/+/g; s/_/\//g')
          # Add padding if necessary
          local remainder=$((${#base64_input_standard} % 4))
          if [ "$remainder" -eq 2 ]; then
              base64_input_standard="${base64_input_standard}=="
          elif [ "$remainder" -eq 3 ]; then
              base64_input_standard="${base64_input_standard}="
          fi

          echo "$base64_input_standard" | base64 --decode 2>/dev/null
        }


