name: Check if feature branch is up to date with develop

on:
  pull_request:
    branches:
      - develop

jobs:
  check-up-to-date:
    runs-on: windows-latest

    steps:
    - name: Checkout feature branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Fetch develop branch
      run: git fetch origin develop

    - name: Check if feature branch is up to date with develop
      run: |
        git merge-base --is-ancestor origin/develop %GITHUB_HEAD_REF%
        if %ERRORLEVEL% neq 0 (
          echo Feature branch is not up to date with develop branch.
          exit /b 1
        )
      shell: cmd