name: Terraform CI/CD

on:
  workflow_dispatch:
  repository_dispatch:
    types: [terraform_apply]

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: terraform

      - name: Verify Directory Structure
        run: ls -al terraform

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: terraform/google-cloud/terraform

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: terraform/google-cloud/terraform

      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan -out=tfplan
      #   working-directory: google-cloud/terraform

      # - name: Terraform Apply
      #   id: apply
      #   run: terraform apply -auto-approve tfplan
      #   working-directory: google-cloud/terraform