# Some example steps 
name: GHA utils

on:
  workflow_dispatch:

jobs:
  utils:
    runs-on: ubuntu-latest

    steps:
    # this step lists the softwares installed on a runner
      - name: List installed softwares on the runner
        run: |
          echo "Listing installed software packages:"
          dpkg --list

    # this step prints the env variables set on the runner
      - name: Print ENVIRONMENT Variables
        run: |
          echo "Printing all ENV vars using printenv:"
          printenv | sort

          echo "Printing all ENV vars using env:"
          env | sort          
